calendarapp/cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    url(r'^goal/new/$', views.goal, name='goal_new'),
    url(r'^goal/edit/(?P<goal_id>\d+)/$', views.goal, name='goal_edit'),
    url(r'^todo/new/$', views.todo, name='todo_new'),
    url(r'^todo/edit/(?P<todo_id>\d+)/$', views.todo, name='todo_edit'),
]

calendarapp/calendarapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('cal.urls')),
]

calendarapp/cal/models.py
from django.db import models
from django.urls import reverse

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

class Goal(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('cal:goal_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

class ToDo(models.Model):
    title=models.CharField(max_length=200)
    date=models.DateTimeField()
    Completed=models.BooleanField(default=False)
    
    @property
    def get_html_url(self):
        url = reverse('cal:todo_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'
    

calendarapp/cal/forms.py
from django.forms import ModelForm, DateInput
from cal.models import Event, Goal, ToDo
from django import forms

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

class GoalForm(ModelForm):
  class Meta:
    model = Goal
    widgets = {
      'date': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(GoalForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['date'].input_formats = ('%Y-%m-%dT%H:%M',)
    

class ToDoForm(forms.ModelForm):
  class Meta:
    model = ToDo
    widgets = {
      'date': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'
  def __init__(self, *args, **kwargs):
    super(ToDoForm, self).__init__(*args, **kwargs)
   

  

calendarapp/cal/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.conf import settings
import calendar
import random
import os
import sys
from .models import *
from .utils import Calendar
from .forms import EventForm, GoalForm, ToDoForm

cwd=os.getcwd()
files=os.listdir(cwd)
print("Files in %r: %s" % (cwd, files))

def index(request):
    return HttpResponse('hello')

def home(request):
    today = datetime.now().strftime("%I:%M%p on %B %d, %Y")
    with open(os.path.join(sys.path[0], "quotes.txt"), "r") as f:
        fdata=f.readlines()
        quote=random.choice(fdata)
    return render(request, 'cal/home.html', {'today': today, 'quote': quote})

class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
    
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/event.html', {'form': form})

def goal(request, goal_id=None):
    instance = Goal()
    if goal_id:
        instance = get_object_or_404(Goal, pk=goal_id)
    else:
        instance = Goal()
    
    form = GoalForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/goal.html', {'form': form})

def todo(request, todo_id=None):
    instace = ToDo()
    if todo_id:
        instance = get_object_or_404(ToDo, pk=todo_id)
    else:
        instance = ToDo()

    form=ToDoForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/todo.html', {'form': form})

calendarapp/cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <link rel="icon" href="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/microsoft/209/calendar_1f4c5.png">
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>PlanIt Planner</title>
</head>
<body style="background-color: #33355b">
  {% block content %}
  {% endblock %}

</body>
</html>

calendarapp/cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}
PlanIt Planner
{% endblock %}

{% block content %}
<div class="clearfix" style="background-color:#6d7297;">
	<p style="font-family: Verdana,Geneva,sans-serif; font-size:40px; color:white;"> 📅 PlanIt Planner </p>
	<center>
	<a class="btn btn-info left"
		style="color:#33355b; background-color:white;"
		href="{% url 'cal:calendar' %}?{{ prev_month }}" > ◄ Previous Month </a>

	<a class="btn btn-info mid"
		style="color:#33355b; background-color:white;"
		href="{% url 'cal:home' %}"> 🏠 Home </a>

	<a class="btn btn-info mid"
		style="color:#33355b; background-color:white;"
		href="{% url 'cal:event_new' %}"> 📌 New Event </a>

	<a class="btn btn-info right"
		style="color:#33355b; background-color:white;"
		href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month ► </a>

	<a class="btn btn-info mid"
		style="color:#33355b; background-color:white;"
		href="{% url 'cal:goal_new' %}"> 🌟 New Goal </a>

	<a class="btn btn-info mid"
		style="color:#33355b; background-color:white;"
		href="{% url 'cal:todo_new' %}"> ☑️ New To-Do </a>
	</center>
</div>
<body style="background-color:#33355b;"></body>

<style>

.calendar {
  width: 98%;
  margin: auto;
  font-size: 13px;
  background: white;
}

.calendar tr, .calendar td {
  border: 1px solid #33355b;
}

.calendar th {
  padding: 10px;
  text-align: center;
  background: #6d7297;
  font-size: 18px;
  color: white;
}

.calendar td {
  width: 200px;
  height: 150px;
  padding: 20px 0px 0px 5px;
}

.month {
  font-size: 25px;
  color: white;
}

.date {
  font-size: 16px;
}
</style>

{{ calendar }}
{% endblock %}

calendarapp/cal/templates/cal/daily.html
{% extends 'cal/base.html' %}

{% block title %}
Daily View
{% endblock %}

{% block content %}
<div class="clearfix" style="background-color:#6d7297;">
    <p style="font-family: Verdana,Geneva,sans-serif; font-size:40px;"> 📅 PlanIt Planner </p>

    <a class="btn btn-info right" href="{% url 'cal:calendar' %}"> 📅 Calendar </a>
    <a class="btn btn-info left" href="{% url 'cal:home' %}"> 🏠 Home </a>
    <a class="btn btn-info right" href="{% url 'cal:event_new' %}"> 📌 New Event </a>
</div>

<div class="home">
    {{ today }}
</div>
{% endblock %}

calendarapp/cal/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix" style="color: white; background-color:#6d7297;">
  <p style="font-family: Verdana,Geneva,sans-serif; font-size:40px;"> 📅 PlanIt Planner </p>

  <a class="btn btn-info left"
      style="color:#33355b; background-color:white;"
      href="{% url 'cal:calendar' %}"> 📅 Calendar </a>
</div>

<div class="clearfix" style="color: white;">
  <p style="font-size: 25px; text-align: center;">
      Add an Event
  </p>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table" style="background-color: white;">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>

{% endblock %}

calendarapp/cal/templates/cal/goal.html
{% extends 'cal/base.html' %}

{% block title %}
Goal
{% endblock %}

{% block content %}
<div class="clearfix" style="color: white; background-color:#6d7297;">
  <p style="font-family: Verdana,Geneva,sans-serif; font-size:40px;"> 📅 PlanIt Planner </p>

  <a class="btn btn-info left"
      style="color:#33355b; background-color:white;"
      href="{% url 'cal:calendar' %}"> 📅 Calendar </a>
</div>

<div class="clearfix" style="color: white;">
    <p style="font-size: 25px; text-align: center;">
        Add a Goal
    </p>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table" style="background-color: white; background-clip: padding-box;">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>

{% endblock %}

calendarapp/cal/templates/cal/home.html
{% extends 'cal/base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div class="clearfix" style="background-color:#6d7297;">
    <p style="font-family: Verdana,Geneva,sans-serif; font-size:40px; color: white;"> 📅 PlanIt Planner </p>

    <a class="btn btn-info left"
        style="color:#33355b; background-color:white;"
        href="{% url 'cal:calendar' %}"> 📅 Calendar </a>

    <a class="btn btn-info right"
		style="color:#33355b; background-color:white;"
		href="{% url 'cal:goal_new' %}"> 🌟 New Goal </a>

	<a class="btn btn-info right"
		style="color:#33355b; background-color:white;"
        href="{% url 'cal:todo_new' %}"> ☑️ New To-Do </a>

    <a class="btn btn-info right"
		style="color:#33355b; background-color:white;"
        href="{% url 'cal:event_new' %}"> 📌 New Event </a>
</div>

<body style="background-color:#33355b;"></body>

<div class="home" style="color: white;">
    {{ today }}
</div>

<div class="home" style="color: white;">
    {{ quote }}
</div>
{% endblock %}

calendarapp/cal/templates/cal/todo.html
{% extends 'cal/base.html' %}

{% block title %}
Add to To-Do List
{% endblock %}

{% block content %}
<div class="clearfix" style="color: white; background-color:#6d7297;">
  <p style="font-family: Verdana,Geneva,sans-serif; font-size:40px;"> 📅 PlanIt Planner </p>

  <a class="btn btn-info left"
      style="color:#33355b; background-color:white;"
      href="{% url 'cal:calendar' %}"> 📅 Calendar </a>
</div>

<div class="clearfix" style="color: white;">
  <p style="font-size: 25px; text-align: center;">
      Add a ToDo
  </p>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table" style="background-color: white;">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}